# Generated by Django 4.1.5 on 2023-06-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProject', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
