# Generated by Django 4.1.5 on 2023-06-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProject', '0003_remove_cliente_id_alter_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
