# Generated by Django 4.2.2 on 2023-06-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newProject", "0004_alter_cliente_correo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Productos",
            fields=[
                ("codigo", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("precio", models.IntegerField(max_length=10)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("alimentos", "alimento"),
                            ("accesorios", "accesorio"),
                            ("higiene_cuidado", "higiene y cuidado"),
                            ("camas_casas", "camas y casas"),
                            ("productos", "producto"),
                        ],
                        default="producto",
                        max_length=25,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
    ]
