# Generated by Django 4.2.2 on 2023-06-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newProject", "0005_productos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="confirmar_contraseña",
            field=models.CharField(default="asd123", max_length=50),
        ),
        migrations.AlterField(
            model_name="productos",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("alimentos", "Alimento."),
                    ("accesorios", "Accesorio."),
                    ("higiene_cuidado", "Higiene y cuidado."),
                    ("camas_casas", "Camas y casas."),
                    ("productos", "Producto."),
                ],
                default="producto",
                max_length=25,
            ),
        ),
    ]
