# Generated by Django 4.2.2 on 2023-06-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newProject", "0007_alter_cliente_confirmar_contraseña"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactos",
            fields=[
                (
                    "id_comentario",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nombres", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=60)),
                ("asunto", models.CharField(max_length=50)),
                ("mensaje", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="productos", name="precio", field=models.IntegerField(),
        ),
    ]
